server {
  listen 80; # Cloud Run requires listening on PORT environment variable, often 8080
  root /usr/share/nginx/html;
  index index.html;
  
  # Configuration to enable Angular's client-side routing
  location / {
    try_files $uri $uri/ /index.html;
  }
}